abstract: Locate per-dist and per-module shared files
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
build_requires: 
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: File-ShareDir
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Inspector: 1.12
  File::Spec: 0.80
  Params::Util: 0.07
  perl: 5.005
version: 0.05
